### ISSUE TITLE
добавить `.pre-commit-hooks.yaml` как и в ci (на pr's и на `master`)

### ISSUE THREAD

**Issue by vtrokhymenko** [SemyonSinchenko/qmlcourse#86]
как пример, но чтобы был именно для текста

```
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
```

также обновить `contributing.md`, указав как именно его запустить и добавить `pre-commit` в зависимости
